#########################################
# Termux WireProxy Configuration
#########################################

# Project Root
PROJECT_DIR="$HOME/termux-wireproxy"

# Binary
WIREPROXY_BIN="wireproxy"

#########################################
# Provider
#########################################

PROVIDER="proton"
PROFILE="us.conf"

#########################################
# Derived Paths
#########################################

ACTIVE_PROVIDER_DIR="$PROJECT_DIR/providers/$PROVIDER"

WG_CONFIG="$ACTIVE_PROVIDER_DIR/$PROFILE"

WIREPROXY_CONFIG="$PROJECT_DIR/configs/wireproxy.conf"

#########################################
# SOCKS5
#########################################

SOCKS_HOST="127.0.0.1"
SOCKS_PORT="25344"

#########################################
# Logging
#########################################

LOG_DIR="$PROJECT_DIR/logs"
LOG_FILE="$LOG_DIR/wireproxy.log"

#########################################
# Runtime
#########################################

STATE_DIR="$PROJECT_DIR/state"

#########################################
# Scripts
#########################################

SCRIPT_DIR="$PROJECT_DIR/scripts"
LIB_DIR="$PROJECT_DIR/lib"

#########################################
# Runtime Files
#########################################

PID_FILE="$STATE_DIR/wireproxy.pid"

#########################################
# Health
#########################################

AUTO_RESTART=true
HEALTH_INTERVAL=60
